### PR TITLE
Update coverflow.cpp

### PR DESCRIPTION
**Pull request by Muzzarino**

### CODE REVIEW

**Comment by Fledge68** [comment]
so what does this do? what does it fix?

**Comment by Muzzarino** [comment]
It expands the vertical space if 4:3 is selected on the wii settings.

**Comment by Fledge68** [comment]
have you compiled this commit? it looks like you're missing a closing parenthesis unless i miss counted.

can you provide images of before and after?

I'd like to commit this. i just need a little more proof.

**Comment by gingerbeardman** [comment]
@Muzzarino  I'm happy to test this if you can provide a binary file as I cannot build it myself.

Thanks!

**Comment by Fledge68** [comment]
@gingerbeardman here you go!
[https://www.mediafire.com/file/qe0t0jb3oh3n3oj/wf5_PR_test_boot.dol/file](url)

**Comment by Fledge68** [comment]
@gingerbeardman test it yet?

**Comment by gingerbeardman** [comment]
Yes, I've tested it. One question:

> It expands the vertical space if 4:3 is selected on the wii settings.

Why is this desirable? Am I missing something?

Here are photos...

With change
- afterIMG_6571
- afterIMG_6572
- afterIMG_6570

Without change
- beforeIMG_6573
- beforeIMG_6576
- beforeIMG_6568

**Comment by gingerbeardman** [comment]
Trying to understand the code
```c
if ((CONF_GetAspectRatio() == CONF_ASPECT_16_9) != s)
	guPerspective(m_projMtx, 45, 16.f / 9.f, .1f, 300.f);
else
	guPerspective(m_projMtx, RadToDeg(2.f * atan(tan(DegToRad(45 / 2) / (4.f / 3.f) * (16.f / 9.f))), 4.f / 3.f, .1f, 300.f);
}
```
for 16:9 aspect a fovy value of 45 is used.
historically this was also used for 4:3

for 4:3 this change now sets the fovy value to the result of the long trigonometry equation, which is 60
this is an increase of 33%

But why 60? 

Personally I like the goal of the new change, but I think this is perhaps a little too much given that the cases do not go as close to the edge as they do in 16:9? Thoughts?

> An increase of 33% uses a value of 60
> An increase of 30% would use a value of 58.5
> An increase of 25% would use a value of 56.25
> An increase of 20% would use a value of 54
>

**Comment by Muzzarino** [comment]
> Trying to understand the code
> 
> ```c
> if ((CONF_GetAspectRatio() == CONF_ASPECT_16_9) != s)
> 	guPerspective(m_projMtx, 45, 16.f / 9.f, .1f, 300.f);
> else
> 	guPerspective(m_projMtx, RadToDeg(2.f * atan(tan(DegToRad(45 / 2) / (4.f / 3.f) * (16.f / 9.f))), 4.f / 3.f, .1f, 300.f);
> }
> ```
> 
> for 16:9 aspect a fov_y value of 45 is used.
> historically this was also used for 4:3
> 
> with this change, the fov_y value for 4:3 is set to the result of the long trig. equation, which is 60.
> i don't understand the equation, but this is an increase of 33%.
> 
> But why 60?
> 
> edit: ah, seems like the correct value for 4:3 as used in devkitpro
> https://github.com/search?q=org%3AdevkitPro+guPerspective&type=Code
> 
> In that case I am OK with this change!
> 
> ps: @Muzzarino please add a description and reasoning, or code comments, with a PR to help us save some time! Thank you!

It increases the output vertical fov to 57.8224 degrees (closer to 60) resulting an open matte 4:3 display to be taller than 16:9 and the trigonometric tangent functions are needed to change the screen expansion direction to make it extend vertical instead of it's default one.

**Comment by gingerbeardman** [comment]
It's easy to see the result of the equation in any programming language. The result is exactly 60. The calculation does not use any variables so the result could be hard-coded, which is what they do in DevKitPro.

**Comment by Muzzarino** [comment]
Try this one:

rad2deg(2.0 * atan(tan(deg2rad(45 / 2)) / (4.0 / 3.0) * (16.0 / 9.0))));

**Comment by gingerbeardman** [comment]
> Try this one:
> 
> rad2deg(2.0 * atan(tan(deg2rad(45 / 2)) / (4.0 / 3.0) * (16.0 / 9.0))));

but that's not what is in the C code in the PR?

**Comment by Muzzarino** [comment]
Tried the php code testing site and it outputted the correct value, now give this one a try:

rad2deg(2.0 * atan(tan(deg2rad(45 / 2)) / (4.0 / 3.0) * (16.0 / 9.0)));

**Comment by gingerbeardman** [comment]
Great, is that what you want in your PR?

**Comment by Muzzarino** [comment]
Yes.

**Comment by Muzzarino** [comment]
I'm sure all the parenthesis are correct after testing it out here:

[http://sandbox.onlinephpfunctions.com/](url)

**Comment by Muzzarino** [comment]
Updated my patch, the vertical expansion should be straightened.

**Comment by Fledge68** [comment]
ok sounds good. but is there a point in having the mathematical equation? since i'm sure it always produces the same value.

**Comment by gingerbeardman** [comment]
I think because it produces a fractional it's worth keeping for clarity, as it's only used in setup (not a loop) in a couple of places so the compiler will replace it with the fixed value

**Pull request merged**
