### PR TITLE
Updated language

### PR DESCRIPTION
**Pull request by CrewMdk**
- Removed obsolete text strings from English and Spanish language files.
 - Translated and modified text strings from the Spanish language.
 - Added text strings to the English and Spanish language files that are in the source code but not in the English language file and therefore are not translated to other languages.
 - Correction in text strings of the source code that did not correspond to its identifier.

### CODE REVIEW

**Comment by eku** [comment]
Could you please explain why you removed English text strings?

**Comment by CrewMdk** [comment]
> Could you please explain why you removed English text strings?

The text was removed from the functions, I see no point in having it and in new translations it would not be convenient to translate text that will no longer be used.

https://github.com/Fledge68/WiiFlow_Lite/commit/85c0f05b6db030e7c6a8435790e2d659aa2f7879

**Comment by eku** [comment]
> The text was removed from the functions [85c0f05](https://github.com/Fledge68/WiiFlow_Lite/commit/85c0f05b6db030e7c6a8435790e2d659aa2f7879), I see no point in having it

Are there any other languages with this obsolete string?

**Comment by CrewMdk** [comment]
> Are there any other languages with this obsolete string?

If all other languages ​​include the obsolete text strings.

**Comment by Fledge68** [comment]
i accepted your PR but will be changing wbfsoperr6=Install game is broken, please use cleanrip. back to wbfsoperr6=Install game is broken,\n please use cleanrip.

the \n is used to make 'please use cleanrip' on a second line. otherwise its too much text to fit on one line.

**Pull request merged**
