### PR TITLE
Add proxy support, fix timeouts & update wolfSSL

### PR DESCRIPTION
**Pull request by wiidev**

### CODE REVIEW

**Comment by gingerbeardman** [comment]
@wiidev thoughts appreciated on https://github.com/Fledge68/WiiFlow_Lite/issues/192 which seems to point into an incompatibility being introduced when SSL was added

**Comment by wiidev** [comment]
@gingerbeardman It wouldn't make sense for it to be caused by the wolfSSL lib because the networking code has nothing to do with game launching and games launch correctly with USB Loader GX.

v5.4.0 [contained a lot of changes](https://github.com/Fledge68/WiiFlow_Lite/compare/v5.2.0...v.5.4.0) and more than a few of the commits contain multiple fixes. But I'd look into the commits like [this](https://github.com/Fledge68/WiiFlow_Lite/commit/7bf04b023d22978ead69240ca60eefbea42d1139), [this](https://github.com/Fledge68/WiiFlow_Lite/commit/703abe85775bee4aaffeddb72efc1a3c0332e64c) or [this](https://github.com/Fledge68/WiiFlow_Lite/commit/5fb7a5af5ebfb9c0249f936667dabba99d27379f) instead.

**Comment by gingerbeardman** [comment]
Many thanks!

**Comment by wiidev** [comment]
@gingerbeardman I posted a few test versions to #192, just in case a specific wolfSSL function is doing something weird. At least that way we can prove if there's an issue with the lib.

If the normal version sometimes fails then I'd expect the test version to work. But if all 3 fail then the issues not caused by the wolfSSL lib.

**Comment by wiidev** [comment]
@gingerbeardman I posted a few test versions to #192, just in case a specific wolfSSL function is doing something weird. At least that way we can prove if there is or isn't an issue with the lib.

If the normal version sometimes fails then I'd expect the test version to work. But if all 3 fail then the issues not caused by the wolfSSL lib.

**Comment by wiidev** [comment]
@gingerbeardman I posted a few test versions to #192, just in case a specific wolfSSL function is doing something weird. At least that way we can prove if there is or isn't an issue with the lib.

If the normal version sometimes fails then I'd expect the test version to work. But if all 3 fail then the issues not caused by the wolfSSL lib.

**Pull request merged**
