### PR TITLE
Deflicker settings and video patching fixes

### PR DESCRIPTION
**Pull request by wiidev**

### CODE REVIEW

**Comment by eku** [comment]
Hi @wiidev and @Fledge68
did you notice that the new setting `Deflicker Filter` is not horizontal aligned with the other settings.

**Comment by gingerbeardman** [comment]
@eku the theme you are using was made before this setting, so will need updating.

**Comment by eku** [comment]
> I think the theme you are using was made before this setting existed

I'm pretty sure that this is the case for all existing themes. Are you sure that all of them need to be updated? That can't be, can it?

**Comment by gingerbeardman** [comment]
Sadly that is the case.

**Comment by eku** [comment]
Aaah, I get it. That's the downside of configurability. So, let's hope that the author of `Rhapsodii Shima` will adjust his theme after the next official version of WFL.

**Pull request merged**
