### PR TITLE
fix wad shared content installation

### PR DESCRIPTION
**Pull request by w3irDv**
The "Install WAD" WF code makes no distinction between wad shared content and regular content, and installs all of them in /titles/... This can lead to different problems when trying to execute a wad if the shared content it needs was not installed previously by other means in the emunand.

This PR modifies the code in order to:
- installs the shared content in /shared1
- register it in content.map

only in the mios==false "side" of the execution flow.

Any comment/improvement will be appreciated.

### CODE REVIEW

**Review by LadyE215 — COMMENTED** [review]
[](https://github.com/robmadole/obsidian-brain/tree/master)

**Comment by Fledge68** [comment]
hey are you still around?  the only thing is i noticed a couple of printf.  shouldn't they be gprintf?

if so i can accept the PR and then just make a new commit changing those.

**Comment by Fledge68** [comment]
since there was  conflict (my fault) i added this manually and committed it with acknowledging you as the coder. hope you don't mind.

**Comment by w3irDv** [comment]
Thanks for your review. You are right!!  I'll fix them and I'll update the PR tomorrow. Let me see if  I can do something about the boot.dol/bins folder locally.

**Comment by w3irDv** [comment]
Ok! Seems we have crossed mesages.

**Pull request closed without merging**
